title: Dquan's LLM Notes
description: Open discussions on working with LLMs
baseurl: "/llm-engineering-notes"
url: "https://dangquan1402.github.io"
theme: minima

author: Quan Dang

show_excerpts: true

header_pages:
  - about.md
